---
# tasks file for packages

- name: Updating all packages on the host
  package:
    name: '*'
    state: latest
    
  
- name: Installing a list of packages on the host if not present
  package:
    name: "{{ package_name }}"
    state: present